LOADING THE DATA INTO A DATAFRAME

In [ ]:
import pandas as pd

##Fixing UnicodeDecodeError in position 1709
##Inspecting for the actual encoding of the Source file as it failed to load with the default encoding
import chardet
with open(r"../data/raw/DataCoSupplyChainDataset.csv","rb") as f:
    raw=f.read(100000)
result=chardet.detect(raw)

##Using the encoding detected
df=pd.read_csv(r"../data/raw/DataCoSupplyChainDataset.csv",encoding=result['encoding'])

UNDERSTANDING THE DATA

In [2]:
print("SIZE\n",df.shape)
print("DATA TYPES\n",df.dtypes)

SIZE
 (180519, 53)
DATA TYPES
 Type                                 str
Days for shipping (real)           int64
Days for shipment (scheduled)      int64
Benefit per order                float64
Sales per customer               float64
Delivery Status                      str
Late_delivery_risk                 int64
Category Id                        int64
Category Name                        str
Customer City                        str
Customer Country                     str
Customer Email                       str
Customer Fname                       str
Customer Id                        int64
Customer Lname                       str
Customer Password                    str
Customer Segment                     str
Customer State                       str
Customer Street                      str
Customer Zipcode                 float64
Department Id                      int64
Department Name                      str
Latitude                         float64
Longitude                        float64
Market                               str
Order City                           str
Order Country                        str
Order Customer Id                  int64
order date (DateOrders)              str
Order Id                           int64
Order Item Cardprod Id             int64
Order Item Discount              float64
Order Item Discount Rate         float64
Order Item Id                      int64
Order Item Product Price         float64
Order Item Profit Ratio          float64
Order Item Quantity                int64
Sales                            float64
Order Item Total                 float64
Order Profit Per Order           float64
Order Region                         str
Order State                          str
Order Status                         str
Order Zipcode                    float64
Product Card Id                    int64
Product Category Id                int64
Product Description              float64
Product Image                        str
Product Name                         str
Product Price                    float64
Product Status                     int64
shipping date (DateOrders)           str
Shipping Mode                        str
dtype: object

In [ ]:
#Size and datatypes along with column wise non-null value counts
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 180519 entries, 0 to 180518
Data columns (total 53 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   Type                           180519 non-null  str
 1   Days for shipping (real)       180519 non-null  int64
 2   Days for shipment (scheduled)  180519 non-null  int64
 3   Benefit per order              180519 non-null  float64
 4   Sales per customer             180519 non-null  float64
 5   Delivery Status                180519 non-null  str
 6   Late_delivery_risk             180519 non-null  int64
 7   Category Id                    180519 non-null  int64
 8   Category Name                  180519 non-null  str
 9   Customer City                  180519 non-null  str
 10  Customer Country               180519 non-null  str
 11  Customer Email                 180519 non-null  str
 12  Customer Fname                 180519 non-null  str
 13  Customer Id                    180519 non-null  int64
 14  Customer Lname                 180511 non-null  str
 15  Customer Password              180519 non-null  str
 16  Customer Segment               180519 non-null  str
 17  Customer State                 180519 non-null  str
 18  Customer Street                180519 non-null  str
 19  Customer Zipcode               180516 non-null  float64
 20  Department Id                  180519 non-null  int64
 21  Department Name                180519 non-null  str
 22  Latitude                       180519 non-null  float64
 23  Longitude                      180519 non-null  float64
 24  Market                         180519 non-null  str
 25  Order City                     180519 non-null  str
 26  Order Country                  180519 non-null  str
 27  Order Customer Id              180519 non-null  int64
 28  order date (DateOrders)        180519 non-null  str
 29  Order Id                       180519 non-null  int64
 30  Order Item Cardprod Id         180519 non-null  int64
 31  Order Item Discount            180519 non-null  float64
 32  Order Item Discount Rate       180519 non-null  float64
 33  Order Item Id                  180519 non-null  int64
 34  Order Item Product Price       180519 non-null  float64
 35  Order Item Profit Ratio        180519 non-null  float64
 36  Order Item Quantity            180519 non-null  int64
 37  Sales                          180519 non-null  float64
 38  Order Item Total               180519 non-null  float64
 39  Order Profit Per Order         180519 non-null  float64
 40  Order Region                   180519 non-null  str
 41  Order State                    180519 non-null  str
 42  Order Status                   180519 non-null  str
 43  Order Zipcode                  24840 non-null   float64
 44  Product Card Id                180519 non-null  int64
 45  Product Category Id            180519 non-null  int64
 46  Product Description            0 non-null       float64
 47  Product Image                  180519 non-null  str
 48  Product Name                   180519 non-null  str
 49  Product Price                  180519 non-null  float64
 50  Product Status                 180519 non-null  int64
 51  shipping date (DateOrders)     180519 non-null  str
 52  Shipping Mode                  180519 non-null  str
dtypes: float64(15), int64(14), str(24)
memory usage: 73.0 MB

In [4]:
df.head() #first 5 rows

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,...,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Image,Product Name,Product Price,Product Status,shipping date (DateOrders),Shipping Mode
0,DEBIT,3,4,91.250000,314.640015,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2/3/2018 22:56,Standard Class
1,TRANSFER,5,4,-249.089996,311.359985,Late delivery,1,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/18/2018 12:27,Standard Class
2,CASH,4,4,-247.779999,309.720001,Shipping on time,0,73,Sporting Goods,San Jose,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/17/2018 12:06,Standard Class
3,DEBIT,3,4,22.860001,304.809998,Advance shipping,0,73,Sporting Goods,Los Angeles,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/16/2018 11:45,Standard Class
4,PAYMENT,2,4,134.210007,298.250000,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/15/2018 11:24,Standard Class

In [5]:
df.tail() #last 5 rows

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,...,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Image,Product Name,Product Price,Product Status,shipping date (DateOrders),Shipping Mode
180514,CASH,4,4,40.000000,399.980011,Shipping on time,0,45,Fishing,Brooklyn,...,NaN,1004,45,NaN,http://images.acmesports.sports/Field+%26+Stre...,Field & Stream Sportsman 16 Gun Fire Safe,399.980011,0,1/20/2016 3:40,Standard Class
180515,DEBIT,3,2,-613.770019,395.980011,Late delivery,1,45,Fishing,Bakersfield,...,NaN,1004,45,NaN,http://images.acmesports.sports/Field+%26+Stre...,Field & Stream Sportsman 16 Gun Fire Safe,399.980011,0,1/19/2016 1:34,Second Class
180516,TRANSFER,5,4,141.110001,391.980011,Late delivery,1,45,Fishing,Bristol,...,NaN,1004,45,NaN,http://images.acmesports.sports/Field+%26+Stre...,Field & Stream Sportsman 16 Gun Fire Safe,399.980011,0,1/20/2016 21:00,Standard Class
180517,PAYMENT,3,4,186.229996,387.980011,Advance shipping,0,45,Fishing,Caguas,...,NaN,1004,45,NaN,http://images.acmesports.sports/Field+%26+Stre...,Field & Stream Sportsman 16 Gun Fire Safe,399.980011,0,1/18/2016 20:18,Standard Class
180518,PAYMENT,4,4,168.949997,383.980011,Shipping on time,0,45,Fishing,Caguas,...,NaN,1004,45,NaN,http://images.acmesports.sports/Field+%26+Stre...,Field & Stream Sportsman 16 Gun Fire Safe,399.980011,0,1/19/2016 18:54,Standard Class

In [6]:
df.sample(5) #5 sample rows randomly from within

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,...,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Image,Product Name,Product Price,Product Status,shipping date (DateOrders),Shipping Mode
12826,DEBIT,5,4,54.279999,113.089996,Late delivery,1,18,Men's Footwear,Caguas,...,NaN,403,18,NaN,http://images.acmesports.sports/Nike+Men%27s+C...,Nike Men's CJ Elite 2 TD Football Cleat,129.990005,0,10/3/2017 22:56,Standard Class
178391,DEBIT,5,4,56.000000,124.449997,Late delivery,1,46,Indoor/Outdoor Games,Dayton,...,NaN,1014,46,NaN,http://images.acmesports.sports/O%27Brien+Men%...,O'Brien Men's Neoprene Life Vest,49.980000,0,5/11/2015 17:31,Standard Class
47392,PAYMENT,2,4,-79.949997,117.570000,Advance shipping,0,29,Shop By Sport,Hialeah,...,NaN,627,29,NaN,http://images.acmesports.sports/Under+Armour+G...,Under Armour Girls' Toddler Spine Surge Runni,39.990002,0,1/12/2016 22:35,Standard Class
92245,PAYMENT,2,4,23.900000,191.210007,Advance shipping,0,6,Tennis & Racquet,Caguas,...,NaN,116,6,NaN,http://images.acmesports.sports/Nike+Men%27s+C...,Nike Men's Comfort 2 Slide,44.990002,0,2/2/2015 3:27,Standard Class
167985,PAYMENT,3,4,12.600000,180.000000,Advance shipping,0,24,Women's Apparel,Oceanside,...,NaN,502,24,NaN,http://images.acmesports.sports/Nike+Men%27s+D...,Nike Men's Dri-FIT Victory Golf Polo,50.000000,0,9/19/2015 19:57,Standard Class

CROSS CHECKING THE LOADED DATA AGAINST THE DETAILS IN THE DATA DESCRIPTION/DATA DICTIONARY FILE:

In [8]:
ddf=pd.read_csv(r"../data/raw/DescriptionDataCoSupplyChain.csv")
display(ddf)

,FIELDS,DESCRIPTION
0,Type,: Type of transaction made
1,Days for shipping (real),: Actual shipping days of the purchased product
2,Days for shipment (scheduled),: Days of scheduled delivery of the purchased...
3,Benefit per order,: Earnings per order placed
4,Sales per customer,: Total sales per customer made per customer
5,Delivery Status,: Delivery status of orders: Advance shipping...
6,Late_delivery_risk,: Categorical variable that indicates if send...
7,Category Id,: Product category code
8,Category Name,: Description of the product category
9,Customer City,: City where the customer made the purchase
10,Customer Country,: Country where the customer made the purchase
11,Customer Email,: Customer's email
12,Customer Fname,: Customer name
13,Customer Id,: Customer ID
14,Customer Lname,: Customer lastname
15,Customer Password,: Masked customer key
16,Customer Segment,": Types of Customers: Consumer , Corporate , ..."
17,Customer State,: State to which the store where the purchase...
18,Customer Street,: Street to which the store where the purchas...
19,Customer Zipcode,: Customer Zipcode
20,Department Id,: Department code of store
21,Department Name,: Department name of store
22,Latitude,: Latitude corresponding to location of store
23,Longitude,: Longitude corresponding to location of store
24,Market,: Market to where the order is delivered : Af...
25,Order City,: Destination city of the order
26,Order Country,: Destination country of the order
27,Order Customer Id,: Customer order code
28,order date (DateOrders),: Date on which the order is made
29,Order Id,: Order code
30,Order Item Cardprod Id,: Product code generated through the RFID reader
31,Order Item Discount,: Order item discount value
32,Order Item Discount Rate,: Order item discount percentage
33,Order Item Id,: Order item code
34,Order Item Product Price,: Price of products without discount
35,Order Item Profit Ratio,: Order Item Profit Ratio
36,Order Item Quantity,: Number of products per order
37,Sales,: Value in sales
38,Order Item Total,: Total amount per order
39,Order Profit Per Order,: Order Profit Per Order
40,Order Region,: Region of the world where the order is deli...
41,Order State,: State of the region where the order is deli...
42,Order Status,": Order Status : COMPLETE , PENDING , CLOSED ..."
43,Product Card Id,: Product code
44,Product Category Id,: Product category code
45,Product Description,: Product Description
46,Product Image,: Link of visit and purchase of the product
47,Product Name,: Product Name
48,Product Price,: Product Price
49,Product Status,: Status of the product stock :If it is 1 not...
50,Shipping date (DateOrders),: Exact date and time of shipment
51,Shipping Mode,: The following shipping modes are presented ...

In [10]:
print("Comparing fields Customer State and Order State",(df["Customer State"]==df["Order State"]).value_counts())
print("Comparing fields Customer City and Order City",(df["Customer City"]==df["Order City"]).value_counts())

Comparing fields Customer State and Order State False    180519
Name: count, dtype: int64
Comparing fields Customer City and Order City False    180390
True        129
Name: count, dtype: int64

In [11]:
pd.crosstab(df["Customer City"] == df["Order City"], df["Customer State"] == df["Order State"])

col_0   False
row_0
False  180390
True      129

In [24]:
print("Unique Customer Cities",df["Customer City"].nunique())
print(df["Customer City"].value_counts())
print("Unique Customer Countries",df["Customer Country"].nunique())
print(df["Customer Country"].value_counts())

Unique Customer Cities 563
Customer City
Caguas         66770
Chicago         3885
Los Angeles     3417
Brooklyn        3412
New York        1816
               ...
Bartlett          25
Ponce             22
Malden            22
Freehold          13
CA                 3
Name: count, Length: 563, dtype: int64
Unique Customer Countries 2
Customer Country
EE. UU.        111146
Puerto Rico     69373
Name: count, dtype: int64

OBSERVATIONS after cross checking the data:
1.All columns present in the data as per the Description file.Date fields need to be converted to date type from str type before calculations.
2.Customer City/state/street/country represents origin/store location(pos for purchase).
3.Order City/state/country/region represent the actual delivery location.
    (observations 2 and 3 above were clarified through three different checks,as the description file alone could be a bit confusing particularly for those particular fields. The CHECKS:1. Through the Labeling in the description file. 2. Through cross tab match- 'Customer State' and 'Order State' never matched for any of the rows. 3.Unique value check- 'Customer Country' has only 2 unique values, showing concentrated store location countries/pos countries.)

4.The store origin - delivery destination pair is going to be used for distance based emission estimation.
5.Latitude and Longitude fields only gives store side coordinates.Therefore a geocoding step needs to be done for delivery destination.

MISSING VALUES CHECK and DUPLICATES CHECK

In [ ]:
#MISSING VALUES CHECK
missing=df.isnull().sum() #counts the null values against each column
missing=missing[missing>0].reset_index() #creating a dataframe of only the columns with missing values
missing.columns=["Column","Missing Values"] #assigning column headers
missing["Missing Percentage"] = (missing["Missing Values"] / len(df) * 100).round(4) #percentage of missing values columnwise
display(missing)

                Column  Missing Values  Missing Percentage
0       Customer Lname               8              0.0044
1     Customer Zipcode               3              0.0017
2        Order Zipcode          155679             86.2397
3  Product Description          180519            100.0000

In [33]:
#DUPLICATES CHECK
df.duplicated().sum()

np.int64(0)

OBSERVATIONS:
1.Customer Lastname and Customer Zipcode columns had only an insignificant small percentage of Missing values.But Order Zipcode and   Product Description has significantly high percentage of missing values.

2.There are No Duplicates in the Data.

Next steps:Inspect and handle missing values, Validate dates and convert datatypes,standardizing, constructing event logs.