LOADING THE DATA INTO A DATAFRAME

In [376]:
import pandas as pd

##Fixing UnicodeDecodeError in position 1709
##Inspecting for the actual encoding of the Source file as it failed to load with the default encoding
import chardet
with open(r"../data/raw/DataCoSupplyChainDataset.csv","rb") as f:
    raw=f.read(100000)
result=chardet.detect(raw)

##Using the encoding detected
df=pd.read_csv(r"../data/raw/DataCoSupplyChainDataset.csv",encoding=result['encoding'])

UNDERSTANDING THE DATA

In [377]:
rows_initial,cols_initial=df.shape #count of rows and columns of the original data.
cols_list_initial=df.columns.to_list() #list of column names in the original data.
cols_list_initial=[x.lower().strip() for x in cols_list_initial]
print("SIZE\n",df.shape)
print("DATA TYPES\n",df.dtypes)

SIZE
 (180519, 53)
DATA TYPES
 Type                                 str
Days for shipping (real)           int64
Days for shipment (scheduled)      int64
Benefit per order                float64
Sales per customer               float64
Delivery Status                      str
Late_delivery_risk                 int64
Category Id                        int64
Category Name                        str
Customer City                        str
Customer Country                     str
Customer Email                       str
Customer Fname                       str
Customer Id                        int64
Customer Lname                       str
Customer Password                    str
Customer Segment                     str
Customer State                       str
Customer Street                      str
Customer Zipcode                 float64
Department Id                      int64
Department Name                      str
Latitude                         float64
Longitude                        float64
Market                               str
Order City                           str
Order Country                        str
Order Customer Id                  int64
order date (DateOrders)              str
Order Id                           int64
Order Item Cardprod Id             int64
Order Item Discount              float64
Order Item Discount Rate         float64
Order Item Id                      int64
Order Item Product Price         float64
Order Item Profit Ratio          float64
Order Item Quantity                int64
Sales                            float64
Order Item Total                 float64
Order Profit Per Order           float64
Order Region                         str
Order State                          str
Order Status                         str
Order Zipcode                    float64
Product Card Id                    int64
Product Category Id                int64
Product Description              float64
Product Image                        str
Product Name                         str
Product Price                    float64
Product Status                     int64
shipping date (DateOrders)           str
Shipping Mode                        str
dtype: object

In [378]:
#Size and datatypes along with column wise non-null value counts
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 180519 entries, 0 to 180518
Data columns (total 53 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   Type                           180519 non-null  str
 1   Days for shipping (real)       180519 non-null  int64
 2   Days for shipment (scheduled)  180519 non-null  int64
 3   Benefit per order              180519 non-null  float64
 4   Sales per customer             180519 non-null  float64
 5   Delivery Status                180519 non-null  str
 6   Late_delivery_risk             180519 non-null  int64
 7   Category Id                    180519 non-null  int64
 8   Category Name                  180519 non-null  str
 9   Customer City                  180519 non-null  str
 10  Customer Country               180519 non-null  str
 11  Customer Email                 180519 non-null  str
 12  Customer Fname                 180519 non-null  str
 13  Customer Id                    180519 non-null  int64
 14  Customer Lname                 180511 non-null  str
 15  Customer Password              180519 non-null  str
 16  Customer Segment               180519 non-null  str
 17  Customer State                 180519 non-null  str
 18  Customer Street                180519 non-null  str
 19  Customer Zipcode               180516 non-null  float64
 20  Department Id                  180519 non-null  int64
 21  Department Name                180519 non-null  str
 22  Latitude                       180519 non-null  float64
 23  Longitude                      180519 non-null  float64
 24  Market                         180519 non-null  str
 25  Order City                     180519 non-null  str
 26  Order Country                  180519 non-null  str
 27  Order Customer Id              180519 non-null  int64
 28  order date (DateOrders)        180519 non-null  str
 29  Order Id                       180519 non-null  int64
 30  Order Item Cardprod Id         180519 non-null  int64
 31  Order Item Discount            180519 non-null  float64
 32  Order Item Discount Rate       180519 non-null  float64
 33  Order Item Id                  180519 non-null  int64
 34  Order Item Product Price       180519 non-null  float64
 35  Order Item Profit Ratio        180519 non-null  float64
 36  Order Item Quantity            180519 non-null  int64
 37  Sales                          180519 non-null  float64
 38  Order Item Total               180519 non-null  float64
 39  Order Profit Per Order         180519 non-null  float64
 40  Order Region                   180519 non-null  str
 41  Order State                    180519 non-null  str
 42  Order Status                   180519 non-null  str
 43  Order Zipcode                  24840 non-null   float64
 44  Product Card Id                180519 non-null  int64
 45  Product Category Id            180519 non-null  int64
 46  Product Description            0 non-null       float64
 47  Product Image                  180519 non-null  str
 48  Product Name                   180519 non-null  str
 49  Product Price                  180519 non-null  float64
 50  Product Status                 180519 non-null  int64
 51  shipping date (DateOrders)     180519 non-null  str
 52  Shipping Mode                  180519 non-null  str
dtypes: float64(15), int64(14), str(24)
memory usage: 73.0 MB

In [379]:
df.head() #first 5 rows

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,...,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Image,Product Name,Product Price,Product Status,shipping date (DateOrders),Shipping Mode
0,DEBIT,3,4,91.250000,314.640015,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,02/03/2018 22:56,Standard Class
1,TRANSFER,5,4,-249.089996,311.359985,Late delivery,1,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/18/2018 12:27,Standard Class
2,CASH,4,4,-247.779999,309.720001,Shipping on time,0,73,Sporting Goods,San Jose,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/17/2018 12:06,Standard Class
3,DEBIT,3,4,22.860001,304.809998,Advance shipping,0,73,Sporting Goods,Los Angeles,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/16/2018 11:45,Standard Class
4,PAYMENT,2,4,134.210007,298.250000,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/15/2018 11:24,Standard Class

In [380]:
df.tail() #last 5 rows

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,...,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Image,Product Name,Product Price,Product Status,shipping date (DateOrders),Shipping Mode
180514,CASH,4,4,40.000000,399.980011,Shipping on time,0,45,Fishing,Brooklyn,...,NaN,1004,45,NaN,http://images.acmesports.sports/Field+%26+Stre...,Field & Stream Sportsman 16 Gun Fire Safe,399.980011,0,1/20/2016 3:40,Standard Class
180515,DEBIT,3,2,-613.770019,395.980011,Late delivery,1,45,Fishing,Bakersfield,...,NaN,1004,45,NaN,http://images.acmesports.sports/Field+%26+Stre...,Field & Stream Sportsman 16 Gun Fire Safe,399.980011,0,1/19/2016 1:34,Second Class
180516,TRANSFER,5,4,141.110001,391.980011,Late delivery,1,45,Fishing,Bristol,...,NaN,1004,45,NaN,http://images.acmesports.sports/Field+%26+Stre...,Field & Stream Sportsman 16 Gun Fire Safe,399.980011,0,1/20/2016 21:00,Standard Class
180517,PAYMENT,3,4,186.229996,387.980011,Advance shipping,0,45,Fishing,Caguas,...,NaN,1004,45,NaN,http://images.acmesports.sports/Field+%26+Stre...,Field & Stream Sportsman 16 Gun Fire Safe,399.980011,0,1/18/2016 20:18,Standard Class
180518,PAYMENT,4,4,168.949997,383.980011,Shipping on time,0,45,Fishing,Caguas,...,NaN,1004,45,NaN,http://images.acmesports.sports/Field+%26+Stre...,Field & Stream Sportsman 16 Gun Fire Safe,399.980011,0,1/19/2016 18:54,Standard Class

In [381]:
df.sample(5) #5 sample rows randomly from within

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,...,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Image,Product Name,Product Price,Product Status,shipping date (DateOrders),Shipping Mode
174435,CASH,6,4,43.189999,89.989998,Late delivery,1,17,Cleats,Caguas,...,55106.0,365,17,NaN,http://images.acmesports.sports/Perfect+Fitnes...,Perfect Fitness Perfect Rip Deck,59.990002,0,04/09/2016 06:43,Standard Class
76285,PAYMENT,0,0,12.300000,163.990005,Shipping on time,0,48,Water Sports,Bronx,...,NaN,1073,48,NaN,http://images.acmesports.sports/Pelican+Sunstr...,Pelican Sunstream 100 Kayak,199.990005,0,2/17/2015 13:09,Same Day
115210,DEBIT,2,4,97.440002,335.980011,Advance shipping,0,45,Fishing,Caguas,...,NaN,1004,45,NaN,http://images.acmesports.sports/Field+%26+Stre...,Field & Stream Sportsman 16 Gun Fire Safe,399.980011,0,9/19/2017 12:37,Standard Class
111668,PAYMENT,3,2,70.529999,146.940002,Late delivery,1,46,Indoor/Outdoor Games,Portland,...,NaN,1014,46,NaN,http://images.acmesports.sports/O%27Brien+Men%...,O'Brien Men's Neoprene Life Vest,49.980000,0,12/18/2016 17:13,Second Class
47367,PAYMENT,3,4,53.990002,224.979996,Advance shipping,0,9,Cardio Equipment,Mechanicsburg,...,NaN,191,9,NaN,http://images.acmesports.sports/Nike+Men%27s+F...,Nike Men's Free 5.0+ Running Shoe,99.989998,0,1/13/2016 1:55,Standard Class

CROSS CHECKING THE LOADED DATA AGAINST THE DETAILS IN THE DATA DESCRIPTION/DATA DICTIONARY FILE:

In [382]:
ddf=pd.read_csv(r"../data/raw/DescriptionDataCoSupplyChain.csv")
display(ddf)

,FIELDS,DESCRIPTION
0,Type,: Type of transaction made
1,Days for shipping (real),: Actual shipping days of the purchased product
2,Days for shipment (scheduled),: Days of scheduled delivery of the purchased...
3,Benefit per order,: Earnings per order placed
4,Sales per customer,: Total sales per customer made per customer
5,Delivery Status,: Delivery status of orders: Advance shipping...
6,Late_delivery_risk,: Categorical variable that indicates if send...
7,Category Id,: Product category code
8,Category Name,: Description of the product category
9,Customer City,: City where the customer made the purchase
10,Customer Country,: Country where the customer made the purchase
11,Customer Email,: Customer's email
12,Customer Fname,: Customer name
13,Customer Id,: Customer ID
14,Customer Lname,: Customer lastname
15,Customer Password,: Masked customer key
16,Customer Segment,": Types of Customers: Consumer , Corporate , ..."
17,Customer State,: State to which the store where the purchase...
18,Customer Street,: Street to which the store where the purchas...
19,Customer Zipcode,: Customer Zipcode
20,Department Id,: Department code of store
21,Department Name,: Department name of store
22,Latitude,: Latitude corresponding to location of store
23,Longitude,: Longitude corresponding to location of store
24,Market,: Market to where the order is delivered : Af...
25,Order City,: Destination city of the order
26,Order Country,: Destination country of the order
27,Order Customer Id,: Customer order code
28,order date (DateOrders),: Date on which the order is made
29,Order Id,: Order code
30,Order Item Cardprod Id,: Product code generated through the RFID reader
31,Order Item Discount,: Order item discount value
32,Order Item Discount Rate,: Order item discount percentage
33,Order Item Id,: Order item code
34,Order Item Product Price,: Price of products without discount
35,Order Item Profit Ratio,: Order Item Profit Ratio
36,Order Item Quantity,: Number of products per order
37,Sales,: Value in sales
38,Order Item Total,: Total amount per order
39,Order Profit Per Order,: Order Profit Per Order
40,Order Region,: Region of the world where the order is deli...
41,Order State,: State of the region where the order is deli...
42,Order Status,": Order Status : COMPLETE , PENDING , CLOSED ..."
43,Product Card Id,: Product code
44,Product Category Id,: Product category code
45,Product Description,: Product Description
46,Product Image,: Link of visit and purchase of the product
47,Product Name,: Product Name
48,Product Price,: Product Price
49,Product Status,: Status of the product stock :If it is 1 not...
50,Shipping date (DateOrders),: Exact date and time of shipment
51,Shipping Mode,: The following shipping modes are presented ...

In [383]:
#Cross checking Columns of data against columns in data description
print(ddf.shape[0])
print(df.shape[1])

52
53

In [384]:
# print(df.columns.to_list(), )
# print(ddf["FIELDS"].to_list())

In [385]:
if len(ddf["FIELDS"].to_list())==len(df.columns.to_list()):
    print("Number of columns match in data and the data description list ")
if len(df.columns.to_list())> len(ddf["FIELDS"].to_list()):
    print('Data has extra columns than mentioned in the data description',[x for x in df.columns.to_list() if x.strip().lower() not in [y.strip().lower() for y in ddf["FIELDS"].to_list()]]
)          
if len(ddf["FIELDS"].to_list())> len(df.columns.to_list()):
    print('Data has fewer columns than mentioned in the data decription',[x for x in ddf["FIELDS"].to_list() if x.strip().lower() not in [y.strip().lower() for y in df.columns.to_list()]])

Data has extra columns than mentioned in the data description ['Order Zipcode']

In [386]:
# if ddf.shape[0]==df.shape[1]:
#     print("Number of columns match in data and the data description list ")
# if df.shape[1]> ddf.shape[0]:
#     print('Data has more columns than mentioned in the data decription',~df.columns.str.strip().str.lower().isin(ddf["FIELDS"].str.strip().str.lower()))          
# if ddf.shape[0]> df.shape[1]:
#     print('Data has fewer columns than mentioned in the data decription',~ddf["FIELDS"].str.strip().str.lower().isin(df.columns.str.strip().str.lower()))

In [387]:
print("Comparing fields Customer State and Order State",(df["Customer State"]==df["Order State"]).value_counts())
print("Comparing fields Customer City and Order City",(df["Customer City"]==df["Order City"]).value_counts())

Comparing fields Customer State and Order State False    180519
Name: count, dtype: int64
Comparing fields Customer City and Order City False    180390
True        129
Name: count, dtype: int64

In [388]:
pd.crosstab(df["Customer City"] == df["Order City"], df["Customer State"] == df["Order State"])

col_0   False
row_0
False  180390
True      129

In [389]:
print("Unique Customer Cities",df["Customer City"].nunique())
print(df["Customer City"].value_counts())
print("Unique Customer Countries",df["Customer Country"].nunique())
print(df["Customer Country"].value_counts())

Unique Customer Cities 563
Customer City
Caguas         66770
Chicago         3885
Los Angeles     3417
Brooklyn        3412
New York        1816
               ...
Bartlett          25
Ponce             22
Malden            22
Freehold          13
CA                 3
Name: count, Length: 563, dtype: int64
Unique Customer Countries 2
Customer Country
EE. UU.        111146
Puerto Rico     69373
Name: count, dtype: int64

OBSERVATIONS after cross checking the data:
1.'Order Zipcode' is an extra column in the dataset that is not present in the description file. Date fields need to be converted to date type from str type before calculations. All other columns present in the data are as per the Description file.

2.Customer City/state/street/country represents origin/store location(pos for purchase).

3.Order City/state/country/region represent the actual delivery location.
    
    (observations 2 and 3 above were clarified through three different checks,as the description file alone could be a bit confusing particularly for those particular fields. The CHECKS:1. Through the Labeling in the description file. 2. Through cross tab match- 'Customer State' and 'Order State' never matched for any of the rows. 3.Unique value check- 'Customer Country' has only 2 unique values, showing concentrated store location countries/pos countries.)

4.The store origin - delivery destination pair is going to be used for distance based emission estimation.

5.Latitude and Longitude fields only gives store side coordinates.Therefore a geocoding step needs to be done for delivery destination.

MISSING VALUES CHECK and DUPLICATES CHECK

In [390]:
#DUPLICATES CHECK
df.duplicated().sum() #

np.int64(0)

In [391]:
#MISSING VALUES CHECK
#columnwise

missing=df.isnull().sum() #counts the null values against each column
missing=missing[missing>0].reset_index() #creating a dataframe of only the columns with missing values
missing.columns=["Column","Missing Values"] #assigning column headers
missing["Missing Percentage"] = (missing["Missing Values"] / len(df) * 100).round(4) #percentage of missing values columnwise
display(missing)

                Column  Missing Values  Missing Percentage
0       Customer Lname               8              0.0044
1     Customer Zipcode               3              0.0017
2        Order Zipcode          155679             86.2397
3  Product Description          180519            100.0000

In [392]:
#row wise 
rowwise_missing=df.isnull().sum(axis=1) #gives number of missing values in each row
rowwise_missing_percent=(rowwise_missing/df.shape[1]*100).to_frame(name="missing value percent rowwise")
print("Counts",rowwise_missing)
display(rowwise_missing_percent)

Counts 0         2
1         2
2         2
3         2
4         2
         ..
180514    2
180515    2
180516    2
180517    2
180518    2
Length: 180519, dtype: int64

        missing value percent rowwise
0                            3.773585
1                            3.773585
2                            3.773585
3                            3.773585
4                            3.773585
...                               ...
180514                       3.773585
180515                       3.773585
180516                       3.773585
180517                       3.773585
180518                       3.773585

[180519 rows x 1 columns]

OBSERVATIONS:
1.Customer Lastname and Customer Zipcode columns had only an insignificant small percentage of Missing values.But Order Zipcode and   Product Description has significantly high percentage of missing values.

2.There are No Duplicates in the Data.

HANDLING MISSING VALUES

In [393]:
#identifying the list of column names that have missing values ,for each row
df['Missing_Columns']=(df.isnull()).apply(lambda row: list(df.columns[row]), axis=1)

df[['Missing_Columns']].head(10)

                        Missing_Columns
0  [Order Zipcode, Product Description]
1  [Order Zipcode, Product Description]
2  [Order Zipcode, Product Description]
3  [Order Zipcode, Product Description]
4  [Order Zipcode, Product Description]
5  [Order Zipcode, Product Description]
6  [Order Zipcode, Product Description]
7  [Order Zipcode, Product Description]
8  [Order Zipcode, Product Description]
9  [Order Zipcode, Product Description]

In [394]:
# How many times does each column show up as missing, across all rows?
missing_counts_per_col = df.isnull().sum().sort_values(ascending=False)
print(missing_counts_per_col[missing_counts_per_col > 0])

# What are the distinct "missing pattern" combinations, and how common is each?
pattern_counts = df['Missing_Columns'].apply(tuple).value_counts()
print(pattern_counts)

Product Description    180519
Order Zipcode          155679
Customer Lname              8
Customer Zipcode            3
dtype: int64
Missing_Columns
(Order Zipcode, Product Description)                      155668
(Product Description,)                                     24840
(Customer Lname, Order Zipcode, Product Description)           8
(Customer Zipcode, Order Zipcode, Product Description)         3
Name: count, dtype: int64

In [395]:
df = df.drop(columns=['Missing_Columns'])  # drop helper column

Dropping 'Product Description' column first as it is 100% missing and imputing 'Customer Zipcode' with mode.

In [396]:
import numpy as np

#dropping the column with 100% missing
df=df.drop(columns=['Product Description']) 

#rows to impute
rows_to_impute = df[df['Customer Zipcode'].isna()]
print("Rows with missing Customer Zipcode:")
display(rows_to_impute[['Customer City', 'Customer State', 'Customer Zipcode']])
#print(rows_to_impute[['Customer City', 'Customer State', 'Customer Zipcode']])
print("Row positions (index):", rows_to_impute.index.tolist())

#imputing the column with 0.0017% missing.Fill in most common zip code for that city+state combination.
# mode_zip = (
#     df.groupby(['Customer City', 'Customer State'])['Customer Zipcode']
#     .transform(lambda x: x.mode().iloc[0] if not x.mode().empty else np.nan)
# )
# df['Customer Zipcode'] = df['Customer Zipcode'].fillna(mode_zip)

Rows with missing Customer Zipcode:

      Customer City Customer State  Customer Zipcode
35704            CA          95758               NaN
46440            CA          95758               NaN
82511            CA          91732               NaN

Row positions (index): [35704, 46440, 82511]

In [397]:
#All rows with customer city as CA
CA_rows= df[(df['Customer City'].str.strip().str.lower()=="ca")]
print("Rows with customer city as CA:")
display(CA_rows[['Customer City', 'Customer State', 'Customer Zipcode']])

Rows with customer city as CA:

      Customer City Customer State  Customer Zipcode
35704            CA          95758               NaN
46440            CA          95758               NaN
82511            CA          91732               NaN

In [398]:
CA_rows_state=df[df['Customer State'].str.strip().str.lower()=="ca"]
print("Rows with customer state as CA:")
display(CA_rows_state[['Customer City', 'Customer State', 'Customer Zipcode']])

Rows with customer state as CA:

       Customer City Customer State  Customer Zipcode
2           San Jose             CA           95125.0
3        Los Angeles             CA           90027.0
9          San Ramon             CA           94583.0
12           Salinas             CA           93905.0
17         Paramount             CA           90723.0
...              ...            ...               ...
180502         Vista             CA           92083.0
180503         Vista             CA           92083.0
180505      Highland             CA           92346.0
180511   Chula Vista             CA           91911.0
180515   Bakersfield             CA           93304.0

[29223 rows x 3 columns]

After careful Observation, it was found that:

1.The 3 rows for which 'Customer Zipcode' has Null values,'Customer State' has numerical values(95758,95758,91732) which are not valid values for Customer State.

2.Additionally these are the only 3 rows where 'Customer City' value is 'CA' while there are 29223 rows with 'Customer State' as CA.Therefore we could assume 'CA' is not a valid value that belongs to Customer City.

3.This is an indication that it could be a case of incorrect data entry or data capture in the original dataset where- 'Customer State' value was wrongly entered in 'Customer City', 'Customer zipcode' value was wrongly entered in 'Customer State'. The actual field with no values available could be 'Customer City' and not 'Customer Zipcode'.

Since it is only 3 rows, we stop the investigation on this here, not imputing the 'Customer Zipcodes' but leaving it as is for now.

In [399]:
view_df=df[["Customer Id","Customer Fname","Customer Lname","Customer City","Customer State","Customer Zipcode","Customer Country","Order City","Order State","Order Zipcode","Order Country","Order Id","Order Customer Id","Order Item Id"]]
view_df

,Customer Id,Customer Fname,Customer Lname,Customer City,Customer State,Customer Zipcode,Customer Country,Order City,Order State,Order Zipcode,Order Country,Order Id,Order Customer Id,Order Item Id
0,20755,Cally,Holloway,Caguas,PR,725.0,Puerto Rico,Bekasi,Java Occidental,NaN,Indonesia,77202,20755,180517
1,19492,Irene,Luna,Caguas,PR,725.0,Puerto Rico,Bikaner,Rajastán,NaN,India,75939,19492,179254
2,19491,Gillian,Maldonado,San Jose,CA,95125.0,EE. UU.,Bikaner,Rajastán,NaN,India,75938,19491,179253
3,19490,Tana,Tate,Los Angeles,CA,90027.0,EE. UU.,Townsville,Queensland,NaN,Australia,75937,19490,179252
4,19489,Orli,Hendricks,Caguas,PR,725.0,Puerto Rico,Townsville,Queensland,NaN,Australia,75936,19489,179251
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
180514,1005,Maria,Peterson,Brooklyn,NY,11207.0,EE. UU.,Shanghái,Shanghái,NaN,China,26043,1005,65177
180515,9141,Ronald,Clark,Bakersfield,CA,93304.0,EE. UU.,Hirakata,Osaka,NaN,Japón,26037,9141,65161
180516,291,John,Smith,Bristol,CT,6010.0,EE. UU.,Adelaide,Australia del Sur,NaN,Australia,26024,291,65129
180517,2813,Mary,Smith,Caguas,PR,725.0,Puerto Rico,Adelaide,Australia del Sur,NaN,Australia,26022,2813,65126
180518,7547,Andrea,Ortega,Caguas,PR,725.0,Puerto Rico,Nagercoil,Tamil Nadu,NaN,India,26018,7547,65113

In [400]:
rows_after,cols_after=df.shape #number of rows and columns after handling missing values
cols_list_after=df.columns.to_list()#list of column names after handling missing values.
cols_list_after=[x.lower().strip() for x in cols_list_after]
print("COLUMNS DELETED to Handle Missing Values in Data",list(set(cols_list_initial) - set(cols_list_after)))

COLUMNS DELETED to Handle Missing Values in Data ['product description']

Comments on handling Missing Values:

1.The 'Product Description' column dropped as it was 100% missing.

2.'Order Zipcode','Customer Zipcode', 'Customer Lastname' kept with the missing values as -is.

VALIDATING DATE FIELDS

In [401]:
###CHECKING ALL THE DATATYPES
df_col_types= df.dtypes.astype(str).to_dict()
print("Columns with their data types\n",df_col_types) #list of all columns with their datatypes- as a dictionary.

#FINDING DATE COLUMNS,THEIR EXISTING DATATYPE,IDENTIFYING THE FORMAT OF THE VALUES(if DD/MM/YYYY or MM/DD/YYYY)
#  & parsing to DATE data type in the identified format

for column,dtype in df_col_types.items():
    if 'date'in column.lower().strip():   ##identifying date columns
        date_string=df[column].str.strip()
        # CHECKING FOR DATE FORMAT  DD/MM/YYYY or MM/DD/YYYY & Parsing datatype to Date in the identified format
        date_parts = date_string.str.split('/', expand=True)
        day = pd.to_numeric(date_parts[0], errors='coerce')
        month = pd.to_numeric(date_parts[1], errors='coerce')
        # print(date_parts[2])
        dd_mm_format = day > 12
        dd_mm_count = dd_mm_format.sum()
        mm_dd_format = month > 12
        mm_dd_count = mm_dd_format.sum()

        if dd_mm_count>0 & mm_dd_count==0:
            print("******IDENTIFIED DATE FORMAT IS DD/MM/YYYY HH:MM*******")
            # print("BEFORE",df[column])
            df[column] = pd.to_datetime(df[column], format='%d/%m/%Y %H:%M',errors='coerce')
            print("*****Column "+column+ " parsed to datatype DATE******")
        if mm_dd_count>0 & dd_mm_count==0:
            print("******IDENTIFIED DATE FORMAT IS MM/DD/YYYY HH:MM******") 
            # print("BEFORE",df[column])
            df[column] = pd.to_datetime(df[column], format='%m/%d/%Y %H:%M',errors='coerce')
            print("*****Column "+column+ " parsed to datatype DATE******")
# print(df.dtypes)

Columns with their data types
 {'Type': 'str', 'Days for shipping (real)': 'int64', 'Days for shipment (scheduled)': 'int64', 'Benefit per order': 'float64', 'Sales per customer': 'float64', 'Delivery Status': 'str', 'Late_delivery_risk': 'int64', 'Category Id': 'int64', 'Category Name': 'str', 'Customer City': 'str', 'Customer Country': 'str', 'Customer Email': 'str', 'Customer Fname': 'str', 'Customer Id': 'int64', 'Customer Lname': 'str', 'Customer Password': 'str', 'Customer Segment': 'str', 'Customer State': 'str', 'Customer Street': 'str', 'Customer Zipcode': 'float64', 'Department Id': 'int64', 'Department Name': 'str', 'Latitude': 'float64', 'Longitude': 'float64', 'Market': 'str', 'Order City': 'str', 'Order Country': 'str', 'Order Customer Id': 'int64', 'order date (DateOrders)': 'str', 'Order Id': 'int64', 'Order Item Cardprod Id': 'int64', 'Order Item Discount': 'float64', 'Order Item Discount Rate': 'float64', 'Order Item Id': 'int64', 'Order Item Product Price': 'float64', 'Order Item Profit Ratio': 'float64', 'Order Item Quantity': 'int64', 'Sales': 'float64', 'Order Item Total': 'float64', 'Order Profit Per Order': 'float64', 'Order Region': 'str', 'Order State': 'str', 'Order Status': 'str', 'Order Zipcode': 'float64', 'Product Card Id': 'int64', 'Product Category Id': 'int64', 'Product Image': 'str', 'Product Name': 'str', 'Product Price': 'float64', 'Product Status': 'int64', 'shipping date (DateOrders)': 'str', 'Shipping Mode': 'str'}
******IDENTIFIED DATE FORMAT IS MM/DD/YYYY HH:MM******
*****Column order date (DateOrders) parsed to datatype DATE******
******IDENTIFIED DATE FORMAT IS MM/DD/YYYY HH:MM******
*****Column shipping date (DateOrders) parsed to datatype DATE******

RESULTS:

Next steps: Finish validating dates and also other fields datatypes,standardizing, constructing event logs.